import datetime
import os

REPORT_DIR = "incident_reports"

def generate_report(incident_type, resolution, duration_seconds):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"post_mortem_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    
    if not os.path.exists(REPORT_DIR):
        os.makedirs(REPORT_DIR)
        
    filepath = os.path.join(REPORT_DIR, filename)
    
    content = f"""# Incident Post-Mortem

**Date**: {timestamp}
**Incident Type**: {incident_type}
**Resolution Status**: RESOLVED

## Summary
The system detected an anomaly identified as **{incident_type}**. The SRE Agent autonomously intervened.

## Timeline
- **Detection**: {timestamp} (Approx)
- **Diagnosis**: {incident_type} identified from logs.
- **Action**: {resolution}
- **Duration**: {duration_seconds} seconds (estimated)

## Root Cause Analysis
(Automated analysis based on log patterns)
- Detection of `{incident_type}` pattern in logs triggering immediate remediation.

## Action Items
- Monitor for recurrence.
- Review recent deployments if frequent.

---
*Generated by AI SRE Agent*
"""
    
    with open(filepath, "w") as f:
        f.write(content)
    
    print(f"Post-mortem report generated: {filepath}")

def main():
    # In a real integration, these would be passed as args
    generate_report("DB_FAILURE", "Restarted Database Service", 15)

if __name__ == "__main__":
    main()
